name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '**/*.README.md'
      - '**/*.env.example'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /root/my-coding-journey
            git pull origin main
            yarn install
            VITE_SERVER_URL="https://my-coding-journey.com/api" yarn build
            rm -rf /var/www/html/dist
            cp -r dist /var/www/html
            chown -R www-data:www-data /var/www/html/dist
